//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace client_app.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://services.financial-tracker.com/")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string colorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        private bool is_predefinedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                if ((object.ReferenceEquals(this.colorField, value) != true)) {
                    this.colorField = value;
                    this.RaisePropertyChanged("color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool is_predefined {
            get {
                return this.is_predefinedField;
            }
            set {
                if ((this.is_predefinedField.Equals(value) != true)) {
                    this.is_predefinedField = value;
                    this.RaisePropertyChanged("is_predefined");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://services.financial-tracker.com/")]
    [System.SerializableAttribute()]
    public partial class Transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        private decimal amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        private System.Nullable<int> category_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string category_nameField;
        
        private System.DateTime transaction_dateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> category_id {
            get {
                return this.category_idField;
            }
            set {
                if ((this.category_idField.Equals(value) != true)) {
                    this.category_idField = value;
                    this.RaisePropertyChanged("category_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string category_name {
            get {
                return this.category_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.category_nameField, value) != true)) {
                    this.category_nameField = value;
                    this.RaisePropertyChanged("category_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime transaction_date {
            get {
                return this.transaction_dateField;
            }
            set {
                if ((this.transaction_dateField.Equals(value) != true)) {
                    this.transaction_dateField = value;
                    this.RaisePropertyChanged("transaction_date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BudgetRule", Namespace="http://services.financial-tracker.com/")]
    [System.SerializableAttribute()]
    public partial class BudgetRule : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private System.DateTime start_dateField;
        
        private System.Nullable<System.DateTime> end_dateField;
        
        private decimal needs_ratioField;
        
        private decimal wants_ratioField;
        
        private decimal savings_ratioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime start_date {
            get {
                return this.start_dateField;
            }
            set {
                if ((this.start_dateField.Equals(value) != true)) {
                    this.start_dateField = value;
                    this.RaisePropertyChanged("start_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> end_date {
            get {
                return this.end_dateField;
            }
            set {
                if ((this.end_dateField.Equals(value) != true)) {
                    this.end_dateField = value;
                    this.RaisePropertyChanged("end_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal needs_ratio {
            get {
                return this.needs_ratioField;
            }
            set {
                if ((this.needs_ratioField.Equals(value) != true)) {
                    this.needs_ratioField = value;
                    this.RaisePropertyChanged("needs_ratio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal wants_ratio {
            get {
                return this.wants_ratioField;
            }
            set {
                if ((this.wants_ratioField.Equals(value) != true)) {
                    this.wants_ratioField = value;
                    this.RaisePropertyChanged("wants_ratio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal savings_ratio {
            get {
                return this.savings_ratioField;
            }
            set {
                if ((this.savings_ratioField.Equals(value) != true)) {
                    this.savings_ratioField = value;
                    this.RaisePropertyChanged("savings_ratio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryTotal", Namespace="http://services.financial-tracker.com/")]
    [System.SerializableAttribute()]
    public partial class CategoryTotal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        private decimal TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.financial-tracker.com/", ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name GetCategoriesResult from namespace http://services.financial-tracker.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/GetCategories", ReplyAction="*")]
        client_app.ServiceReference1.GetCategoriesResponse GetCategories(client_app.ServiceReference1.GetCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/GetCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<client_app.ServiceReference1.GetCategoriesResponse> GetCategoriesAsync(client_app.ServiceReference1.GetCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://services.financial-tracker.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/AddCategory", ReplyAction="*")]
        client_app.ServiceReference1.AddCategoryResponse AddCategory(client_app.ServiceReference1.AddCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/AddCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<client_app.ServiceReference1.AddCategoryResponse> AddCategoryAsync(client_app.ServiceReference1.AddCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://services.financial-tracker.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/UpdateCategory", ReplyAction="*")]
        client_app.ServiceReference1.UpdateCategoryResponse UpdateCategory(client_app.ServiceReference1.UpdateCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/UpdateCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<client_app.ServiceReference1.UpdateCategoryResponse> UpdateCategoryAsync(client_app.ServiceReference1.UpdateCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/DeleteCategory", ReplyAction="*")]
        void DeleteCategory(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/DeleteCategory", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteCategoryAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetTransactionsResult from namespace http://services.financial-tracker.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/GetTransactions", ReplyAction="*")]
        client_app.ServiceReference1.GetTransactionsResponse GetTransactions(client_app.ServiceReference1.GetTransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/GetTransactions", ReplyAction="*")]
        System.Threading.Tasks.Task<client_app.ServiceReference1.GetTransactionsResponse> GetTransactionsAsync(client_app.ServiceReference1.GetTransactionsRequest request);
        
        // CODEGEN: Generating message contract since element name description from namespace http://services.financial-tracker.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/AddTransaction", ReplyAction="*")]
        client_app.ServiceReference1.AddTransactionResponse AddTransaction(client_app.ServiceReference1.AddTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/AddTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<client_app.ServiceReference1.AddTransactionResponse> AddTransactionAsync(client_app.ServiceReference1.AddTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name description from namespace http://services.financial-tracker.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/UpdateTransaction", ReplyAction="*")]
        client_app.ServiceReference1.UpdateTransactionResponse UpdateTransaction(client_app.ServiceReference1.UpdateTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/UpdateTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<client_app.ServiceReference1.UpdateTransactionResponse> UpdateTransactionAsync(client_app.ServiceReference1.UpdateTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/DeleteTransaction", ReplyAction="*")]
        void DeleteTransaction(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/DeleteTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteTransactionAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetBudgetRulesResult from namespace http://services.financial-tracker.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/GetBudgetRules", ReplyAction="*")]
        client_app.ServiceReference1.GetBudgetRulesResponse GetBudgetRules(client_app.ServiceReference1.GetBudgetRulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/GetBudgetRules", ReplyAction="*")]
        System.Threading.Tasks.Task<client_app.ServiceReference1.GetBudgetRulesResponse> GetBudgetRulesAsync(client_app.ServiceReference1.GetBudgetRulesRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://services.financial-tracker.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/AddBudgetRule", ReplyAction="*")]
        client_app.ServiceReference1.AddBudgetRuleResponse AddBudgetRule(client_app.ServiceReference1.AddBudgetRuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/AddBudgetRule", ReplyAction="*")]
        System.Threading.Tasks.Task<client_app.ServiceReference1.AddBudgetRuleResponse> AddBudgetRuleAsync(client_app.ServiceReference1.AddBudgetRuleRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://services.financial-tracker.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/UpdateBudgetRule", ReplyAction="*")]
        client_app.ServiceReference1.UpdateBudgetRuleResponse UpdateBudgetRule(client_app.ServiceReference1.UpdateBudgetRuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/UpdateBudgetRule", ReplyAction="*")]
        System.Threading.Tasks.Task<client_app.ServiceReference1.UpdateBudgetRuleResponse> UpdateBudgetRuleAsync(client_app.ServiceReference1.UpdateBudgetRuleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/DeleteBudgetRule", ReplyAction="*")]
        void DeleteBudgetRule(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/DeleteBudgetRule", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteBudgetRuleAsync(int id);
        
        // CODEGEN: Generating message contract since element name GetCategoryTotalsResult from namespace http://services.financial-tracker.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/GetCategoryTotals", ReplyAction="*")]
        client_app.ServiceReference1.GetCategoryTotalsResponse GetCategoryTotals(client_app.ServiceReference1.GetCategoryTotalsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.financial-tracker.com/GetCategoryTotals", ReplyAction="*")]
        System.Threading.Tasks.Task<client_app.ServiceReference1.GetCategoryTotalsResponse> GetCategoryTotalsAsync(client_app.ServiceReference1.GetCategoryTotalsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategories", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.GetCategoriesRequestBody Body;
        
        public GetCategoriesRequest() {
        }
        
        public GetCategoriesRequest(client_app.ServiceReference1.GetCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCategoriesRequestBody {
        
        public GetCategoriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoriesResponse", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.GetCategoriesResponseBody Body;
        
        public GetCategoriesResponse() {
        }
        
        public GetCategoriesResponse(client_app.ServiceReference1.GetCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class GetCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public client_app.ServiceReference1.Category[] GetCategoriesResult;
        
        public GetCategoriesResponseBody() {
        }
        
        public GetCategoriesResponseBody(client_app.ServiceReference1.Category[] GetCategoriesResult) {
            this.GetCategoriesResult = GetCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCategory", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.AddCategoryRequestBody Body;
        
        public AddCategoryRequest() {
        }
        
        public AddCategoryRequest(client_app.ServiceReference1.AddCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class AddCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string color;
        
        public AddCategoryRequestBody() {
        }
        
        public AddCategoryRequestBody(string name, string type, string description, string color) {
            this.name = name;
            this.type = type;
            this.description = description;
            this.color = color;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCategoryResponse", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.AddCategoryResponseBody Body;
        
        public AddCategoryResponse() {
        }
        
        public AddCategoryResponse(client_app.ServiceReference1.AddCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class AddCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddCategoryResult;
        
        public AddCategoryResponseBody() {
        }
        
        public AddCategoryResponseBody(int AddCategoryResult) {
            this.AddCategoryResult = AddCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCategory", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.UpdateCategoryRequestBody Body;
        
        public UpdateCategoryRequest() {
        }
        
        public UpdateCategoryRequest(client_app.ServiceReference1.UpdateCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class UpdateCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string color;
        
        public UpdateCategoryRequestBody() {
        }
        
        public UpdateCategoryRequestBody(int id, string name, string type, string description, string color) {
            this.id = id;
            this.name = name;
            this.type = type;
            this.description = description;
            this.color = color;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCategoryResponse", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.UpdateCategoryResponseBody Body;
        
        public UpdateCategoryResponse() {
        }
        
        public UpdateCategoryResponse(client_app.ServiceReference1.UpdateCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateCategoryResponseBody {
        
        public UpdateCategoryResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTransactions", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.GetTransactionsRequestBody Body;
        
        public GetTransactionsRequest() {
        }
        
        public GetTransactionsRequest(client_app.ServiceReference1.GetTransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTransactionsRequestBody {
        
        public GetTransactionsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTransactionsResponse", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.GetTransactionsResponseBody Body;
        
        public GetTransactionsResponse() {
        }
        
        public GetTransactionsResponse(client_app.ServiceReference1.GetTransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class GetTransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public client_app.ServiceReference1.Transaction[] GetTransactionsResult;
        
        public GetTransactionsResponseBody() {
        }
        
        public GetTransactionsResponseBody(client_app.ServiceReference1.Transaction[] GetTransactionsResult) {
            this.GetTransactionsResult = GetTransactionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTransaction", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.AddTransactionRequestBody Body;
        
        public AddTransactionRequest() {
        }
        
        public AddTransactionRequest(client_app.ServiceReference1.AddTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class AddTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> category_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime transaction_date;
        
        public AddTransactionRequestBody() {
        }
        
        public AddTransactionRequestBody(string description, decimal amount, string type, System.Nullable<int> category_id, System.DateTime transaction_date) {
            this.description = description;
            this.amount = amount;
            this.type = type;
            this.category_id = category_id;
            this.transaction_date = transaction_date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTransactionResponse", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.AddTransactionResponseBody Body;
        
        public AddTransactionResponse() {
        }
        
        public AddTransactionResponse(client_app.ServiceReference1.AddTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class AddTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddTransactionResult;
        
        public AddTransactionResponseBody() {
        }
        
        public AddTransactionResponseBody(int AddTransactionResult) {
            this.AddTransactionResult = AddTransactionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTransaction", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.UpdateTransactionRequestBody Body;
        
        public UpdateTransactionRequest() {
        }
        
        public UpdateTransactionRequest(client_app.ServiceReference1.UpdateTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class UpdateTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> category_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime transaction_date;
        
        public UpdateTransactionRequestBody() {
        }
        
        public UpdateTransactionRequestBody(int id, string description, decimal amount, string type, System.Nullable<int> category_id, System.DateTime transaction_date) {
            this.id = id;
            this.description = description;
            this.amount = amount;
            this.type = type;
            this.category_id = category_id;
            this.transaction_date = transaction_date;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTransactionResponse", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.UpdateTransactionResponseBody Body;
        
        public UpdateTransactionResponse() {
        }
        
        public UpdateTransactionResponse(client_app.ServiceReference1.UpdateTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateTransactionResponseBody {
        
        public UpdateTransactionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBudgetRulesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBudgetRules", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.GetBudgetRulesRequestBody Body;
        
        public GetBudgetRulesRequest() {
        }
        
        public GetBudgetRulesRequest(client_app.ServiceReference1.GetBudgetRulesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBudgetRulesRequestBody {
        
        public GetBudgetRulesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBudgetRulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBudgetRulesResponse", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.GetBudgetRulesResponseBody Body;
        
        public GetBudgetRulesResponse() {
        }
        
        public GetBudgetRulesResponse(client_app.ServiceReference1.GetBudgetRulesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class GetBudgetRulesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public client_app.ServiceReference1.BudgetRule[] GetBudgetRulesResult;
        
        public GetBudgetRulesResponseBody() {
        }
        
        public GetBudgetRulesResponseBody(client_app.ServiceReference1.BudgetRule[] GetBudgetRulesResult) {
            this.GetBudgetRulesResult = GetBudgetRulesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBudgetRuleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBudgetRule", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.AddBudgetRuleRequestBody Body;
        
        public AddBudgetRuleRequest() {
        }
        
        public AddBudgetRuleRequest(client_app.ServiceReference1.AddBudgetRuleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class AddBudgetRuleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime start_date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> end_date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal needs_ratio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal wants_ratio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal savings_ratio;
        
        public AddBudgetRuleRequestBody() {
        }
        
        public AddBudgetRuleRequestBody(string name, System.DateTime start_date, System.Nullable<System.DateTime> end_date, decimal needs_ratio, decimal wants_ratio, decimal savings_ratio) {
            this.name = name;
            this.start_date = start_date;
            this.end_date = end_date;
            this.needs_ratio = needs_ratio;
            this.wants_ratio = wants_ratio;
            this.savings_ratio = savings_ratio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBudgetRuleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBudgetRuleResponse", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.AddBudgetRuleResponseBody Body;
        
        public AddBudgetRuleResponse() {
        }
        
        public AddBudgetRuleResponse(client_app.ServiceReference1.AddBudgetRuleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class AddBudgetRuleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddBudgetRuleResult;
        
        public AddBudgetRuleResponseBody() {
        }
        
        public AddBudgetRuleResponseBody(int AddBudgetRuleResult) {
            this.AddBudgetRuleResult = AddBudgetRuleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBudgetRuleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBudgetRule", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.UpdateBudgetRuleRequestBody Body;
        
        public UpdateBudgetRuleRequest() {
        }
        
        public UpdateBudgetRuleRequest(client_app.ServiceReference1.UpdateBudgetRuleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class UpdateBudgetRuleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime start_date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> end_date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal needs_ratio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal wants_ratio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal savings_ratio;
        
        public UpdateBudgetRuleRequestBody() {
        }
        
        public UpdateBudgetRuleRequestBody(int id, string name, System.DateTime start_date, System.Nullable<System.DateTime> end_date, decimal needs_ratio, decimal wants_ratio, decimal savings_ratio) {
            this.id = id;
            this.name = name;
            this.start_date = start_date;
            this.end_date = end_date;
            this.needs_ratio = needs_ratio;
            this.wants_ratio = wants_ratio;
            this.savings_ratio = savings_ratio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBudgetRuleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBudgetRuleResponse", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.UpdateBudgetRuleResponseBody Body;
        
        public UpdateBudgetRuleResponse() {
        }
        
        public UpdateBudgetRuleResponse(client_app.ServiceReference1.UpdateBudgetRuleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateBudgetRuleResponseBody {
        
        public UpdateBudgetRuleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryTotalsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoryTotals", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.GetCategoryTotalsRequestBody Body;
        
        public GetCategoryTotalsRequest() {
        }
        
        public GetCategoryTotalsRequest(client_app.ServiceReference1.GetCategoryTotalsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class GetCategoryTotalsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime startDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime endDate;
        
        public GetCategoryTotalsRequestBody() {
        }
        
        public GetCategoryTotalsRequestBody(System.DateTime startDate, System.DateTime endDate) {
            this.startDate = startDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCategoryTotalsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCategoryTotalsResponse", Namespace="http://services.financial-tracker.com/", Order=0)]
        public client_app.ServiceReference1.GetCategoryTotalsResponseBody Body;
        
        public GetCategoryTotalsResponse() {
        }
        
        public GetCategoryTotalsResponse(client_app.ServiceReference1.GetCategoryTotalsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.financial-tracker.com/")]
    public partial class GetCategoryTotalsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public client_app.ServiceReference1.CategoryTotal[] GetCategoryTotalsResult;
        
        public GetCategoryTotalsResponseBody() {
        }
        
        public GetCategoryTotalsResponseBody(client_app.ServiceReference1.CategoryTotal[] GetCategoryTotalsResult) {
            this.GetCategoryTotalsResult = GetCategoryTotalsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : client_app.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<client_app.ServiceReference1.WebService1Soap>, client_app.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client_app.ServiceReference1.GetCategoriesResponse client_app.ServiceReference1.WebService1Soap.GetCategories(client_app.ServiceReference1.GetCategoriesRequest request) {
            return base.Channel.GetCategories(request);
        }
        
        public client_app.ServiceReference1.Category[] GetCategories() {
            client_app.ServiceReference1.GetCategoriesRequest inValue = new client_app.ServiceReference1.GetCategoriesRequest();
            inValue.Body = new client_app.ServiceReference1.GetCategoriesRequestBody();
            client_app.ServiceReference1.GetCategoriesResponse retVal = ((client_app.ServiceReference1.WebService1Soap)(this)).GetCategories(inValue);
            return retVal.Body.GetCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client_app.ServiceReference1.GetCategoriesResponse> client_app.ServiceReference1.WebService1Soap.GetCategoriesAsync(client_app.ServiceReference1.GetCategoriesRequest request) {
            return base.Channel.GetCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<client_app.ServiceReference1.GetCategoriesResponse> GetCategoriesAsync() {
            client_app.ServiceReference1.GetCategoriesRequest inValue = new client_app.ServiceReference1.GetCategoriesRequest();
            inValue.Body = new client_app.ServiceReference1.GetCategoriesRequestBody();
            return ((client_app.ServiceReference1.WebService1Soap)(this)).GetCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client_app.ServiceReference1.AddCategoryResponse client_app.ServiceReference1.WebService1Soap.AddCategory(client_app.ServiceReference1.AddCategoryRequest request) {
            return base.Channel.AddCategory(request);
        }
        
        public int AddCategory(string name, string type, string description, string color) {
            client_app.ServiceReference1.AddCategoryRequest inValue = new client_app.ServiceReference1.AddCategoryRequest();
            inValue.Body = new client_app.ServiceReference1.AddCategoryRequestBody();
            inValue.Body.name = name;
            inValue.Body.type = type;
            inValue.Body.description = description;
            inValue.Body.color = color;
            client_app.ServiceReference1.AddCategoryResponse retVal = ((client_app.ServiceReference1.WebService1Soap)(this)).AddCategory(inValue);
            return retVal.Body.AddCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client_app.ServiceReference1.AddCategoryResponse> client_app.ServiceReference1.WebService1Soap.AddCategoryAsync(client_app.ServiceReference1.AddCategoryRequest request) {
            return base.Channel.AddCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<client_app.ServiceReference1.AddCategoryResponse> AddCategoryAsync(string name, string type, string description, string color) {
            client_app.ServiceReference1.AddCategoryRequest inValue = new client_app.ServiceReference1.AddCategoryRequest();
            inValue.Body = new client_app.ServiceReference1.AddCategoryRequestBody();
            inValue.Body.name = name;
            inValue.Body.type = type;
            inValue.Body.description = description;
            inValue.Body.color = color;
            return ((client_app.ServiceReference1.WebService1Soap)(this)).AddCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client_app.ServiceReference1.UpdateCategoryResponse client_app.ServiceReference1.WebService1Soap.UpdateCategory(client_app.ServiceReference1.UpdateCategoryRequest request) {
            return base.Channel.UpdateCategory(request);
        }
        
        public void UpdateCategory(int id, string name, string type, string description, string color) {
            client_app.ServiceReference1.UpdateCategoryRequest inValue = new client_app.ServiceReference1.UpdateCategoryRequest();
            inValue.Body = new client_app.ServiceReference1.UpdateCategoryRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.type = type;
            inValue.Body.description = description;
            inValue.Body.color = color;
            client_app.ServiceReference1.UpdateCategoryResponse retVal = ((client_app.ServiceReference1.WebService1Soap)(this)).UpdateCategory(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client_app.ServiceReference1.UpdateCategoryResponse> client_app.ServiceReference1.WebService1Soap.UpdateCategoryAsync(client_app.ServiceReference1.UpdateCategoryRequest request) {
            return base.Channel.UpdateCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<client_app.ServiceReference1.UpdateCategoryResponse> UpdateCategoryAsync(int id, string name, string type, string description, string color) {
            client_app.ServiceReference1.UpdateCategoryRequest inValue = new client_app.ServiceReference1.UpdateCategoryRequest();
            inValue.Body = new client_app.ServiceReference1.UpdateCategoryRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.type = type;
            inValue.Body.description = description;
            inValue.Body.color = color;
            return ((client_app.ServiceReference1.WebService1Soap)(this)).UpdateCategoryAsync(inValue);
        }
        
        public void DeleteCategory(int id) {
            base.Channel.DeleteCategory(id);
        }
        
        public System.Threading.Tasks.Task DeleteCategoryAsync(int id) {
            return base.Channel.DeleteCategoryAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client_app.ServiceReference1.GetTransactionsResponse client_app.ServiceReference1.WebService1Soap.GetTransactions(client_app.ServiceReference1.GetTransactionsRequest request) {
            return base.Channel.GetTransactions(request);
        }
        
        public client_app.ServiceReference1.Transaction[] GetTransactions() {
            client_app.ServiceReference1.GetTransactionsRequest inValue = new client_app.ServiceReference1.GetTransactionsRequest();
            inValue.Body = new client_app.ServiceReference1.GetTransactionsRequestBody();
            client_app.ServiceReference1.GetTransactionsResponse retVal = ((client_app.ServiceReference1.WebService1Soap)(this)).GetTransactions(inValue);
            return retVal.Body.GetTransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client_app.ServiceReference1.GetTransactionsResponse> client_app.ServiceReference1.WebService1Soap.GetTransactionsAsync(client_app.ServiceReference1.GetTransactionsRequest request) {
            return base.Channel.GetTransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<client_app.ServiceReference1.GetTransactionsResponse> GetTransactionsAsync() {
            client_app.ServiceReference1.GetTransactionsRequest inValue = new client_app.ServiceReference1.GetTransactionsRequest();
            inValue.Body = new client_app.ServiceReference1.GetTransactionsRequestBody();
            return ((client_app.ServiceReference1.WebService1Soap)(this)).GetTransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client_app.ServiceReference1.AddTransactionResponse client_app.ServiceReference1.WebService1Soap.AddTransaction(client_app.ServiceReference1.AddTransactionRequest request) {
            return base.Channel.AddTransaction(request);
        }
        
        public int AddTransaction(string description, decimal amount, string type, System.Nullable<int> category_id, System.DateTime transaction_date) {
            client_app.ServiceReference1.AddTransactionRequest inValue = new client_app.ServiceReference1.AddTransactionRequest();
            inValue.Body = new client_app.ServiceReference1.AddTransactionRequestBody();
            inValue.Body.description = description;
            inValue.Body.amount = amount;
            inValue.Body.type = type;
            inValue.Body.category_id = category_id;
            inValue.Body.transaction_date = transaction_date;
            client_app.ServiceReference1.AddTransactionResponse retVal = ((client_app.ServiceReference1.WebService1Soap)(this)).AddTransaction(inValue);
            return retVal.Body.AddTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client_app.ServiceReference1.AddTransactionResponse> client_app.ServiceReference1.WebService1Soap.AddTransactionAsync(client_app.ServiceReference1.AddTransactionRequest request) {
            return base.Channel.AddTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<client_app.ServiceReference1.AddTransactionResponse> AddTransactionAsync(string description, decimal amount, string type, System.Nullable<int> category_id, System.DateTime transaction_date) {
            client_app.ServiceReference1.AddTransactionRequest inValue = new client_app.ServiceReference1.AddTransactionRequest();
            inValue.Body = new client_app.ServiceReference1.AddTransactionRequestBody();
            inValue.Body.description = description;
            inValue.Body.amount = amount;
            inValue.Body.type = type;
            inValue.Body.category_id = category_id;
            inValue.Body.transaction_date = transaction_date;
            return ((client_app.ServiceReference1.WebService1Soap)(this)).AddTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client_app.ServiceReference1.UpdateTransactionResponse client_app.ServiceReference1.WebService1Soap.UpdateTransaction(client_app.ServiceReference1.UpdateTransactionRequest request) {
            return base.Channel.UpdateTransaction(request);
        }
        
        public void UpdateTransaction(int id, string description, decimal amount, string type, System.Nullable<int> category_id, System.DateTime transaction_date) {
            client_app.ServiceReference1.UpdateTransactionRequest inValue = new client_app.ServiceReference1.UpdateTransactionRequest();
            inValue.Body = new client_app.ServiceReference1.UpdateTransactionRequestBody();
            inValue.Body.id = id;
            inValue.Body.description = description;
            inValue.Body.amount = amount;
            inValue.Body.type = type;
            inValue.Body.category_id = category_id;
            inValue.Body.transaction_date = transaction_date;
            client_app.ServiceReference1.UpdateTransactionResponse retVal = ((client_app.ServiceReference1.WebService1Soap)(this)).UpdateTransaction(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client_app.ServiceReference1.UpdateTransactionResponse> client_app.ServiceReference1.WebService1Soap.UpdateTransactionAsync(client_app.ServiceReference1.UpdateTransactionRequest request) {
            return base.Channel.UpdateTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<client_app.ServiceReference1.UpdateTransactionResponse> UpdateTransactionAsync(int id, string description, decimal amount, string type, System.Nullable<int> category_id, System.DateTime transaction_date) {
            client_app.ServiceReference1.UpdateTransactionRequest inValue = new client_app.ServiceReference1.UpdateTransactionRequest();
            inValue.Body = new client_app.ServiceReference1.UpdateTransactionRequestBody();
            inValue.Body.id = id;
            inValue.Body.description = description;
            inValue.Body.amount = amount;
            inValue.Body.type = type;
            inValue.Body.category_id = category_id;
            inValue.Body.transaction_date = transaction_date;
            return ((client_app.ServiceReference1.WebService1Soap)(this)).UpdateTransactionAsync(inValue);
        }
        
        public void DeleteTransaction(int id) {
            base.Channel.DeleteTransaction(id);
        }
        
        public System.Threading.Tasks.Task DeleteTransactionAsync(int id) {
            return base.Channel.DeleteTransactionAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client_app.ServiceReference1.GetBudgetRulesResponse client_app.ServiceReference1.WebService1Soap.GetBudgetRules(client_app.ServiceReference1.GetBudgetRulesRequest request) {
            return base.Channel.GetBudgetRules(request);
        }
        
        public client_app.ServiceReference1.BudgetRule[] GetBudgetRules() {
            client_app.ServiceReference1.GetBudgetRulesRequest inValue = new client_app.ServiceReference1.GetBudgetRulesRequest();
            inValue.Body = new client_app.ServiceReference1.GetBudgetRulesRequestBody();
            client_app.ServiceReference1.GetBudgetRulesResponse retVal = ((client_app.ServiceReference1.WebService1Soap)(this)).GetBudgetRules(inValue);
            return retVal.Body.GetBudgetRulesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client_app.ServiceReference1.GetBudgetRulesResponse> client_app.ServiceReference1.WebService1Soap.GetBudgetRulesAsync(client_app.ServiceReference1.GetBudgetRulesRequest request) {
            return base.Channel.GetBudgetRulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<client_app.ServiceReference1.GetBudgetRulesResponse> GetBudgetRulesAsync() {
            client_app.ServiceReference1.GetBudgetRulesRequest inValue = new client_app.ServiceReference1.GetBudgetRulesRequest();
            inValue.Body = new client_app.ServiceReference1.GetBudgetRulesRequestBody();
            return ((client_app.ServiceReference1.WebService1Soap)(this)).GetBudgetRulesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client_app.ServiceReference1.AddBudgetRuleResponse client_app.ServiceReference1.WebService1Soap.AddBudgetRule(client_app.ServiceReference1.AddBudgetRuleRequest request) {
            return base.Channel.AddBudgetRule(request);
        }
        
        public int AddBudgetRule(string name, System.DateTime start_date, System.Nullable<System.DateTime> end_date, decimal needs_ratio, decimal wants_ratio, decimal savings_ratio) {
            client_app.ServiceReference1.AddBudgetRuleRequest inValue = new client_app.ServiceReference1.AddBudgetRuleRequest();
            inValue.Body = new client_app.ServiceReference1.AddBudgetRuleRequestBody();
            inValue.Body.name = name;
            inValue.Body.start_date = start_date;
            inValue.Body.end_date = end_date;
            inValue.Body.needs_ratio = needs_ratio;
            inValue.Body.wants_ratio = wants_ratio;
            inValue.Body.savings_ratio = savings_ratio;
            client_app.ServiceReference1.AddBudgetRuleResponse retVal = ((client_app.ServiceReference1.WebService1Soap)(this)).AddBudgetRule(inValue);
            return retVal.Body.AddBudgetRuleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client_app.ServiceReference1.AddBudgetRuleResponse> client_app.ServiceReference1.WebService1Soap.AddBudgetRuleAsync(client_app.ServiceReference1.AddBudgetRuleRequest request) {
            return base.Channel.AddBudgetRuleAsync(request);
        }
        
        public System.Threading.Tasks.Task<client_app.ServiceReference1.AddBudgetRuleResponse> AddBudgetRuleAsync(string name, System.DateTime start_date, System.Nullable<System.DateTime> end_date, decimal needs_ratio, decimal wants_ratio, decimal savings_ratio) {
            client_app.ServiceReference1.AddBudgetRuleRequest inValue = new client_app.ServiceReference1.AddBudgetRuleRequest();
            inValue.Body = new client_app.ServiceReference1.AddBudgetRuleRequestBody();
            inValue.Body.name = name;
            inValue.Body.start_date = start_date;
            inValue.Body.end_date = end_date;
            inValue.Body.needs_ratio = needs_ratio;
            inValue.Body.wants_ratio = wants_ratio;
            inValue.Body.savings_ratio = savings_ratio;
            return ((client_app.ServiceReference1.WebService1Soap)(this)).AddBudgetRuleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client_app.ServiceReference1.UpdateBudgetRuleResponse client_app.ServiceReference1.WebService1Soap.UpdateBudgetRule(client_app.ServiceReference1.UpdateBudgetRuleRequest request) {
            return base.Channel.UpdateBudgetRule(request);
        }
        
        public void UpdateBudgetRule(int id, string name, System.DateTime start_date, System.Nullable<System.DateTime> end_date, decimal needs_ratio, decimal wants_ratio, decimal savings_ratio) {
            client_app.ServiceReference1.UpdateBudgetRuleRequest inValue = new client_app.ServiceReference1.UpdateBudgetRuleRequest();
            inValue.Body = new client_app.ServiceReference1.UpdateBudgetRuleRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.start_date = start_date;
            inValue.Body.end_date = end_date;
            inValue.Body.needs_ratio = needs_ratio;
            inValue.Body.wants_ratio = wants_ratio;
            inValue.Body.savings_ratio = savings_ratio;
            client_app.ServiceReference1.UpdateBudgetRuleResponse retVal = ((client_app.ServiceReference1.WebService1Soap)(this)).UpdateBudgetRule(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client_app.ServiceReference1.UpdateBudgetRuleResponse> client_app.ServiceReference1.WebService1Soap.UpdateBudgetRuleAsync(client_app.ServiceReference1.UpdateBudgetRuleRequest request) {
            return base.Channel.UpdateBudgetRuleAsync(request);
        }
        
        public System.Threading.Tasks.Task<client_app.ServiceReference1.UpdateBudgetRuleResponse> UpdateBudgetRuleAsync(int id, string name, System.DateTime start_date, System.Nullable<System.DateTime> end_date, decimal needs_ratio, decimal wants_ratio, decimal savings_ratio) {
            client_app.ServiceReference1.UpdateBudgetRuleRequest inValue = new client_app.ServiceReference1.UpdateBudgetRuleRequest();
            inValue.Body = new client_app.ServiceReference1.UpdateBudgetRuleRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.start_date = start_date;
            inValue.Body.end_date = end_date;
            inValue.Body.needs_ratio = needs_ratio;
            inValue.Body.wants_ratio = wants_ratio;
            inValue.Body.savings_ratio = savings_ratio;
            return ((client_app.ServiceReference1.WebService1Soap)(this)).UpdateBudgetRuleAsync(inValue);
        }
        
        public void DeleteBudgetRule(int id) {
            base.Channel.DeleteBudgetRule(id);
        }
        
        public System.Threading.Tasks.Task DeleteBudgetRuleAsync(int id) {
            return base.Channel.DeleteBudgetRuleAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        client_app.ServiceReference1.GetCategoryTotalsResponse client_app.ServiceReference1.WebService1Soap.GetCategoryTotals(client_app.ServiceReference1.GetCategoryTotalsRequest request) {
            return base.Channel.GetCategoryTotals(request);
        }
        
        public client_app.ServiceReference1.CategoryTotal[] GetCategoryTotals(System.DateTime startDate, System.DateTime endDate) {
            client_app.ServiceReference1.GetCategoryTotalsRequest inValue = new client_app.ServiceReference1.GetCategoryTotalsRequest();
            inValue.Body = new client_app.ServiceReference1.GetCategoryTotalsRequestBody();
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            client_app.ServiceReference1.GetCategoryTotalsResponse retVal = ((client_app.ServiceReference1.WebService1Soap)(this)).GetCategoryTotals(inValue);
            return retVal.Body.GetCategoryTotalsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<client_app.ServiceReference1.GetCategoryTotalsResponse> client_app.ServiceReference1.WebService1Soap.GetCategoryTotalsAsync(client_app.ServiceReference1.GetCategoryTotalsRequest request) {
            return base.Channel.GetCategoryTotalsAsync(request);
        }
        
        public System.Threading.Tasks.Task<client_app.ServiceReference1.GetCategoryTotalsResponse> GetCategoryTotalsAsync(System.DateTime startDate, System.DateTime endDate) {
            client_app.ServiceReference1.GetCategoryTotalsRequest inValue = new client_app.ServiceReference1.GetCategoryTotalsRequest();
            inValue.Body = new client_app.ServiceReference1.GetCategoryTotalsRequestBody();
            inValue.Body.startDate = startDate;
            inValue.Body.endDate = endDate;
            return ((client_app.ServiceReference1.WebService1Soap)(this)).GetCategoryTotalsAsync(inValue);
        }
    }
}
